### ISSUE TITLE
Schematic?

### ISSUE THREAD

**Issue by jhall39** [tekk/esp-ledstrip-christmas-2017#1]
Any chance you could share the schematic for how you wired this up?
Thanks!

**Comment by tekk** [comment]
Sure, here u go:
https://www.hackster.io/tekk/knock-controlled-night-light-42c96a

**Comment by tekk** [comment]
There's no schematic at the time, just connect pin 5 of the ESP32 to the data pin of the RGB LED strip and +5V and GND from at least 2A generic power adapter (depends on LED stip length). I've used power adapter which has selectable voltage levels and set it to 5V.

Hope this helps.

**Comment by tekk** [comment]
I may add the photo of the board, but ATM I'm outside my home in Slovakia.

**Comment by tekk** [comment]
In commit No. #[`14f3274`](https://github.com/tekk/esp-ledstrip-christmas-2017/commit/14f3274736bb2cf067362d8e8cb3a79c9636b750) I've added pictures of the box, you can see the wiring there.

I also updated [`README.md`](https://github.com/tekk/esp-ledstrip-christmas-2017) so the pictures are in the readme, for other people asking the same question.
Hope the wiring is clear.
There's nothing complicated in that box...

Hope it helps.

**Comment by tekk** [comment]
Closing `#1`.
